// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRR5ntE1HswKBWeQ86xlEmCfG0b2-FsJQ',
    appId: '1:65495280902:web:aa69c008ce97163e628287',
    messagingSenderId: '65495280902',
    projectId: 'rapid-chat-pro',
    authDomain: 'rapid-chat-pro.firebaseapp.com',
    storageBucket: 'rapid-chat-pro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xCRRflG57ZUZ9FsSpJc3nZNnp9e-c4M',
    appId: '1:65495280902:android:c20d517debc6aaf3628287',
    messagingSenderId: '65495280902',
    projectId: 'rapid-chat-pro',
    storageBucket: 'rapid-chat-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeX6w-Q_UHZMTkISd5PvQXFqjr7L6aNMs',
    appId: '1:65495280902:ios:54de9af12ca661d6628287',
    messagingSenderId: '65495280902',
    projectId: 'rapid-chat-pro',
    storageBucket: 'rapid-chat-pro.appspot.com',
    iosClientId: '65495280902-boutm06vet5en2j66b02sn3r98mt8asn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeX6w-Q_UHZMTkISd5PvQXFqjr7L6aNMs',
    appId: '1:65495280902:ios:b665a01ed4eadad1628287',
    messagingSenderId: '65495280902',
    projectId: 'rapid-chat-pro',
    storageBucket: 'rapid-chat-pro.appspot.com',
    iosClientId: '65495280902-ne92g9lgrbe50bvups7assaak297jmse.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatTalk.RunnerTests',
  );
}
